# Generated by Django 5.1.4 on 2024-12-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(max_length=50)),
                ('subject', models.TextField(blank=True, null=True)),
                ('bookshelf', models.TextField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookDownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='books.book')),
            ],
        ),
    ]
