# Generated by Django 5.1.4 on 2024-12-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
